export * as assetRegistry from './asset-registry/storage'
export * as tokens from './tokens/storage'
export * as omnipool from './omnipool/storage'
export * as stableswap from './stableswap/storage'
export * as xyk from './xyk/storage'
